server {
    listen 80 default_server;
    server_name _;

    location /nginx_status {
        stub_status on;
        allow 172.22.0.10;
        allow 127.0.0.1;
        deny all;
    }

    location / {
        return 444;
    }
}

server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /etc/nginx/ssl/ssl.crt;
    ssl_certificate_key /etc/nginx/ssl/ssl.key;

    return 444;
}